/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package konquest.gui;
/**
 *
 * @author bryan
 */
public class DialogoErrores extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form DialogoErrores
     * @param parent
     * @param modal
     */
    public DialogoErrores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaErroresLexicos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaErroresSintacticos = new javax.swing.JTextArea();
        lblErrores = new javax.swing.JLabel();
        lblErroresLexicos = new javax.swing.JLabel();
        lblErroresLexicos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalisis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaErroresLexicos.setEditable(false);
        txtAreaErroresLexicos.setColumns(20);
        txtAreaErroresLexicos.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaErroresLexicos.setRows(5);
        jScrollPane1.setViewportView(txtAreaErroresLexicos);

        txtAreaErroresSintacticos.setEditable(false);
        txtAreaErroresSintacticos.setColumns(20);
        txtAreaErroresSintacticos.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaErroresSintacticos.setRows(5);
        jScrollPane2.setViewportView(txtAreaErroresSintacticos);

        lblErrores.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblErrores.setText("ERRORES");

        lblErroresLexicos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErroresLexicos.setText("Léxicos:");

        lblErroresLexicos1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErroresLexicos1.setText("Sintacticos:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Información del Analisis:");

        txtAnalisis.setEditable(false);
        txtAnalisis.setColumns(20);
        txtAnalisis.setRows(5);
        jScrollPane3.setViewportView(txtAnalisis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(lblErrores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErroresLexicos1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErroresLexicos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErroresLexicos)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErroresLexicos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void agregarErroresTXTLexico(String ingresar) {
        txtAreaErroresLexicos.setText(txtAreaErroresLexicos.getText() + ingresar + "\n");
    }
    
    public void agregarErroresTXTSintaxis(String ingresar) {
        txtAreaErroresSintacticos.setText(txtAreaErroresSintacticos.getText() + ingresar + "\n");
    }
    
    public void agregarAnalisisTXT(String ingresar){
        txtAnalisis.setText(txtAnalisis.getText() + ingresar + "\n");
    }

    public void limpiarTXTArea(){
        txtAreaErroresLexicos.setText("");
        txtAreaErroresSintacticos.setText("");
        txtAnalisis.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblErrores;
    private javax.swing.JLabel lblErroresLexicos;
    private javax.swing.JLabel lblErroresLexicos1;
    private javax.swing.JTextArea txtAnalisis;
    private javax.swing.JTextArea txtAreaErroresLexicos;
    private javax.swing.JTextArea txtAreaErroresSintacticos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        System.out.println("RUN");
    }
}
