/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konquest.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import konquest.backed.objetos.Ataque;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author bryan
 */
public class DialogListaDeAtaques extends javax.swing.JDialog {
    private List<Ataque> listaAtaques;
    private List<Ataque> listaAtaquesAgregar;
    private ObservableList<Ataque> observableListAtaques;
    private Ataque ataqueCancelar;
    private Ataque ataqueApuntador;
    private Principal principal;
    
    /**
     * Creates new form DialogListaDeAtaques
     */
    public DialogListaDeAtaques(java.awt.Frame parent, boolean modal, List<Ataque> listaAtaquesAgregar, Principal pricipal) {
        super(parent, modal);
        this.listaAtaques = new ArrayList<>();
        this.listaAtaquesAgregar = listaAtaquesAgregar;
        this.observableListAtaques = ObservableCollections.observableList(listaAtaques);
        this.principal = pricipal;
        initComponents();
        updateObservableList(listaAtaquesAgregar);
        this.setLocationRelativeTo(null);  
    }

    public List<Ataque> getListaAtaques() {
        return listaAtaques;
    }

    public void setListaAtaques(List<Ataque> listaAtaques) {
        this.listaAtaques = listaAtaques;
    }

    public List<Ataque> getListaAtaquesAgregar() {
        return listaAtaquesAgregar;
    }

    public void setListaAtaquesAgregar(List<Ataque> listaAtaquesAgregar) {
        this.listaAtaquesAgregar = listaAtaquesAgregar;
    }

    public ObservableList<Ataque> getObservableListAtaques() {
        return observableListAtaques;
    }

    public void setObservableListAtaques(ObservableList<Ataque> observableListAtaques) {
        this.observableListAtaques = observableListAtaques;
    }

    public Ataque getAtaqueCancelar() {
        return ataqueCancelar;
    }

    public void setAtaqueCancelar(Ataque ataqueCancelar) throws CloneNotSupportedException {
        Ataque previus = this.ataqueCancelar;
        if (ataqueCancelar != null) {
            this.ataqueCancelar = ataqueCancelar.clone();
            txtNaves.setText(Integer.toString(this.ataqueCancelar.getNumeroDeNaves()));
            txtPlanetaDetino.setText(this.ataqueCancelar.getPlanetaDestino().getNombre());
            txtPlanetaOrigen.setText(this.ataqueCancelar.getPlanetaOrigen().getNombre());
            txtPorcentajeMuertes.setText(Double.toString(this.ataqueCancelar.getPorcentajeMuertes()));
            txtTurno.setText(Integer.toString(this.ataqueCancelar.getTurnoLlegada()));
            btnCancelarAtaque.setEnabled(true);
        }
        this.ataqueApuntador = ataqueCancelar;
        firePropertyChange("Ataque Seleccionado", previus, this.ataqueCancelar);
    }
    
    public void updateObservableList(List<Ataque> ataqueListObservable) {
        this.observableListAtaques.clear();
        this.observableListAtaques.addAll(ataqueListObservable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaAtaques = new javax.swing.JTable();
        lblListaAtaques = new javax.swing.JLabel();
        txtPlanetaDetino = new javax.swing.JTextField();
        lblAtaque = new javax.swing.JLabel();
        lblPlanetaDestino = new javax.swing.JLabel();
        lblPlanetaDestino1 = new javax.swing.JLabel();
        txtPlanetaOrigen = new javax.swing.JTextField();
        lblNaves = new javax.swing.JLabel();
        txtNaves = new javax.swing.JTextField();
        lblProduccion = new javax.swing.JLabel();
        txtPorcentajeMuertes = new javax.swing.JTextField();
        btnCancelarAtaque = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableListAtaques}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablaListaAtaques);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroDeNaves}"));
        columnBinding.setColumnName("#Naves");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${planetaDestino.nombre}"));
        columnBinding.setColumnName("Planeta Destino");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${planetaOrigen.nombre}"));
        columnBinding.setColumnName("Planeta Origen");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${porcentajeMuertes}"));
        columnBinding.setColumnName("Porcentaje Muertes");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${turnoLlegada}"));
        columnBinding.setColumnName("Turno Llegada");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${ataqueCancelar}"), tablaListaAtaques, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tablaListaAtaques);

        lblListaAtaques.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblListaAtaques.setText("Lista de Ataques");

        txtPlanetaDetino.setEditable(false);

        lblAtaque.setText("Ataque:");

        lblPlanetaDestino.setText("Planeta Destino:");

        lblPlanetaDestino1.setText("Planeta Origen:");

        txtPlanetaOrigen.setEditable(false);

        lblNaves.setText("Naves:");

        txtNaves.setEditable(false);

        lblProduccion.setText(" % Muertes:");

        txtPorcentajeMuertes.setEditable(false);

        btnCancelarAtaque.setText("Cancelar Ataque");
        btnCancelarAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAtaqueActionPerformed(evt);
            }
        });

        lblTurno.setText("Turno:");

        txtTurno.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblListaAtaques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAtaque)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProduccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPorcentajeMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTurno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlanetaDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlanetaDetino, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlanetaDestino1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelarAtaque))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPlanetaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNaves)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblListaAtaques)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlanetaDestino)
                    .addComponent(txtPlanetaDetino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlanetaDestino1)
                    .addComponent(txtPlanetaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaves)
                    .addComponent(txtNaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPorcentajeMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProduccion)
                        .addComponent(btnCancelarAtaque)
                        .addComponent(lblTurno)
                        .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAtaqueActionPerformed
        // TODO add your handling code here:
        if (ataqueApuntador != null) {
            ataqueApuntador.cancelarAtaque();
            if (listaAtaquesAgregar.remove(ataqueApuntador)) {
                principal.getManejadorGUI().actualizarToolText(principal, principal.isMapaCiego());
                JOptionPane.showMessageDialog(null, "Ataque cancelado con exito, las naves estan regresando al planeta de origen.", "Ataque", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Lo siento error al cancelar el ataque.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            limpiar();
            updateObservableList(listaAtaquesAgregar);
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento debes de seleccionar un ataque.");
        }
    }//GEN-LAST:event_btnCancelarAtaqueActionPerformed

    private void limpiar(){
        txtNaves.setText("");
        txtPlanetaDetino.setText("");
        txtPlanetaOrigen.setText("");
        txtPorcentajeMuertes.setText("");
        txtTurno.setText("");
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAtaque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblListaAtaques;
    private javax.swing.JLabel lblNaves;
    private javax.swing.JLabel lblPlanetaDestino;
    private javax.swing.JLabel lblPlanetaDestino1;
    private javax.swing.JLabel lblProduccion;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTable tablaListaAtaques;
    private javax.swing.JTextField txtNaves;
    private javax.swing.JTextField txtPlanetaDetino;
    private javax.swing.JTextField txtPlanetaOrigen;
    private javax.swing.JTextField txtPorcentajeMuertes;
    private javax.swing.JTextField txtTurno;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
