
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package konquest.backed.analizador.partida;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 13;
  public static final int MapaCiego = 9;
  public static final int True = 34;
  public static final int Coma = 32;
  public static final int Ataques = 6;
  public static final int LlaveC = 38;
  public static final int PlanetasNeutrales = 4;
  public static final int LlaveA = 37;
  public static final int Jugador = 25;
  public static final int CantidadProducida = 19;
  public static final int TamañoS = 7;
  public static final int Error = 22;
  public static final int Fila = 17;
  public static final int Columnas = 27;
  public static final int Columna = 18;
  public static final int PlanetaOrigen = 24;
  public static final int NombreJugadores = 40;
  public static final int EOF = 0;
  public static final int DosPuntos = 31;
  public static final int Produccion = 16;
  public static final int Tamaño = 8;
  public static final int CorcheteC = 36;
  public static final int error = 1;
  public static final int CorcheteA = 35;
  public static final int PlanetaDestino = 23;
  public static final int False = 33;
  public static final int NombrePlanetas = 39;
  public static final int Filas = 26;
  public static final int Humano = 28;
  public static final int Tipo = 21;
  public static final int Naves = 14;
  public static final int Planetas = 3;
  public static final int Dificil = 29;
  public static final int PorcentajeMuertes = 15;
  public static final int PlanetasJugadores = 20;
  public static final int Turno = 11;
  public static final int Facil = 30;
  public static final int Mapa = 2;
  public static final int Jugadores = 5;
  public static final int CantidadPlanetas = 12;
  public static final int Decimal = 42;
  public static final int Numero = 41;
  public static final int Finalizacion = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Mapa",
  "Planetas",
  "PlanetasNeutrales",
  "Jugadores",
  "Ataques",
  "TamañoS",
  "Tamaño",
  "MapaCiego",
  "Finalizacion",
  "Turno",
  "CantidadPlanetas",
  "Nombre",
  "Naves",
  "PorcentajeMuertes",
  "Produccion",
  "Fila",
  "Columna",
  "CantidadProducida",
  "PlanetasJugadores",
  "Tipo",
  "Error",
  "PlanetaDestino",
  "PlanetaOrigen",
  "Jugador",
  "Filas",
  "Columnas",
  "Humano",
  "Dificil",
  "Facil",
  "DosPuntos",
  "Coma",
  "False",
  "True",
  "CorcheteA",
  "CorcheteC",
  "LlaveA",
  "LlaveC",
  "NombrePlanetas",
  "NombreJugadores",
  "Numero",
  "Decimal"
  };
}

