
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package konquest.backed.analizador.replay;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 5;
  public static final int PathCarpeta = 15;
  public static final int Menor = 11;
  public static final int Replay = 2;
  public static final int Error = 7;
  public static final int Mayor = 10;
  public static final int Division = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PathCPK = 13;
  public static final int Texto = 4;
  public static final int Archivo = 3;
  public static final int Ubicacion = 6;
  public static final int Identificador = 12;
  public static final int PathTXT = 14;
  public static final int Igual = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Replay",
  "Archivo",
  "Texto",
  "Nombre",
  "Ubicacion",
  "Error",
  "Igual",
  "Division",
  "Mayor",
  "Menor",
  "Identificador",
  "PathCPK",
  "PathTXT",
  "PathCarpeta"
  };
}

