
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package konquest.backed.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 18;
  public static final int MapaCiego = 11;
  public static final int True = 31;
  public static final int Coma = 29;
  public static final int LlaveC = 35;
  public static final int PlanetasNeutrales = 4;
  public static final int LlaveA = 34;
  public static final int Neutrales = 14;
  public static final int TamañoS = 7;
  public static final int Error = 41;
  public static final int Columnas = 24;
  public static final int NombreJugadores = 37;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int DosPuntos = 28;
  public static final int Produccion = 17;
  public static final int Tamaño = 8;
  public static final int CorcheteC = 33;
  public static final int error = 1;
  public static final int CorcheteA = 32;
  public static final int Acumular = 12;
  public static final int False = 30;
  public static final int NombrePlanetas = 36;
  public static final int Filas = 23;
  public static final int Humano = 25;
  public static final int Tipo = 22;
  public static final int PlanetasNeutralesMapa = 10;
  public static final int Planetas = 3;
  public static final int Naves = 19;
  public static final int AlAzar = 9;
  public static final int Dificil = 26;
  public static final int PorcentajeMuertes = 20;
  public static final int PlanetasJugadores = 21;
  public static final int Identificador = 38;
  public static final int Facil = 27;
  public static final int Mapa = 2;
  public static final int Jugadores = 5;
  public static final int MostrarEstadisticas = 16;
  public static final int Decimal = 40;
  public static final int MostrarNaves = 15;
  public static final int Numero = 39;
  public static final int Finalizacion = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Mapa",
  "Planetas",
  "PlanetasNeutrales",
  "Jugadores",
  "ID",
  "TamañoS",
  "Tamaño",
  "AlAzar",
  "PlanetasNeutralesMapa",
  "MapaCiego",
  "Acumular",
  "Finalizacion",
  "Neutrales",
  "MostrarNaves",
  "MostrarEstadisticas",
  "Produccion",
  "Nombre",
  "Naves",
  "PorcentajeMuertes",
  "PlanetasJugadores",
  "Tipo",
  "Filas",
  "Columnas",
  "Humano",
  "Dificil",
  "Facil",
  "DosPuntos",
  "Coma",
  "False",
  "True",
  "CorcheteA",
  "CorcheteC",
  "LlaveA",
  "LlaveC",
  "NombrePlanetas",
  "NombreJugadores",
  "Identificador",
  "Numero",
  "Decimal",
  "Error"
  };
}

